### ISSUE TITLE
Settings file not found when updating

### ISSUE THREAD

**Issue by csmorley** [nogic1008/WritableOptions.Net#157]
If there is no appsettings.json then the application throws an error. Currently I get around it with the below:

```
    private static void AddEnrollmentSettingsFile(HostBuilderContext hostContext, IServiceCollection services)
    {
        // Per https://github.com/nogic1008/WritableOptions.Net
        var enrollmentSettingsPath = Path.Combine(AppConfigPath, EnrollmentSettingsFileName);
        services.ConfigureWritable<EnrollmentSettings>(
            hostContext.Configuration.GetSection(nameof(EnrollmentSettings)),
            enrollmentSettingsPath);

        if (File.Exists(enrollmentSettingsPath) == false)
            File.AppendAllText(enrollmentSettingsPath, "{" + Environment.NewLine + "}");
    }

```
Anything that would do this for me, without the above workaround?

Also is adding the settings file that will be modified via host builder `ConfigureAppConfiguration((hostContext, config) => config.AddJsonFile(settingsPath))` needed?

Thanks for the great library, working great!

**Comment by nogic1008** [comment]
@csmorley 
Thank you for using my library and reporting issue.
It can be solved by creating a new JSON file at some point, but which timing is better?
1. On `IServiceCollection.ConfigureWritable<T>()` called
2. On `JsonWritableOptions.Updete()` called
