### ISSUE TITLE
Enable Source Link

### ISSUE THREAD

**Issue by hymccord** [nogic1008/WritableOptions.Net#165]
Allows developers to source step external NuGets
https://github.com/dotnet/sourcelink

I'll submit a PR shortly to resolve

**Comment by nogic1008** [comment]
@hymccord 
Thank you for your contributing!
`.snupkg` file is now released with main package.
![GitHub Actions log](https://user-images.githubusercontent.com/24802730/209484334-daa5ab22-9caf-4714-901e-5b01e3781a03.png)
