### ISSUE TITLE
Problems with commented file

### ISSUE THREAD

**Issue by franklupo** [nogic1008/WritableOptions.Net#308]
Hi,
wonderful work. I have problems with commented files.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/invalid-json

Best regrds

**Comment by nogic1008** [comment]
@franklupo 
Thank you for your contribution!

[In official docs](https://learn.microsoft.com/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#comments-in-appsettingsjson), comments within appsettings.json are allowed.
But it is not implemented in this library.

I think it can be resolved by passing appropriate `JsonSerializerOptions`. I will try.

PR is welcome.

**Comment by franklupo** [comment]
Yes, `JsonSerializerOptions` is the solution. Pass parameter in `ConfigureWritable, ConfigureWritableWithExplicitPath` or in `Update`?

**Comment by nogic1008** [comment]
@franklupo 
Fixed on #313.
But currently, `JsonWritableOptions.Update()` removes comments & trailing comma even if there are on other section.
This known issue will be tracked in #314.
