### ISSUE TITLE
Unable to reload in a Blazor Server App

### ISSUE THREAD

**Issue by TorreyGarland** [nogic1008/WritableOptions.Net#64]
Hi,

I downloaded the nuget package but ran into some problems with missing dependencies.

So I try cloning this repo to test with a sandbox Blazor server app.

Everything works except that I noticed that when the parameter is set to "true", the reload does not happen because the IConfigurationRoot instance that is injected is always null (doesn't break, just doesn't reload).

Any suggestions?

**Comment by nogic1008** [comment]
@TorreyGarland 
Could you provide a minimal sample of the Blazor server app?
I want to know use case.

**Comment by TorreyGarland** [comment]
please disregard.  Iwritableoptions works, but I have to swap using IOptionMonitor`1 instead of IOptions`1 to pick up the changes.  

Cheers.

**Comment by acornautomation-jon** [comment]
@TorreyGarland could you elaborate on your fix? It seems I am seeing the same issue as you - when registering using ConfigureWritableOptions, sending the IConfiguration from context.Configuration, the "reload" option has no effect.
This means when doing the following, the out-of-date version of settings is returned instead:
`
_options.Update(newValue, true);
var settingsValue = _options.Value; //this is returning the original value - not newValue
`

When debugging, _configuration in the "if (reload)" statement is null.

**Comment by TorreyGarland** [comment]
Geez, this was so long ago...

**Comment by acornautomation-jon** [comment]
@nogic1008, let me know if I should open a new issue.
I believe the issue is that "IConfigurationRoot" is not a service that can be resolved, at least in a WebApplicationHost context - so when the ServiceCollectionExtension is used, the IConfiguration is always null. I believe the solution is to simply resolve "IConfiguration" instead of IConfigurationRoot - this seems to create a valid, reloading instances of WritableOptions.

**Comment by TorreyGarland** [comment]
I appears to work it you use the derived JsonWritableOptions<TOptions> only instead of IOptions<TOptions>.  Any page that injects just IOptions<T> does not appear to reflect changes.

**Comment by nogic1008** [comment]
I don't know Blazor app well, so I want to read sample code.
PR is welcome.
